Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()Traceback (most recent call last):
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 559, in connect

  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    sock = self._connect()    
pubsub.get_message(ignore_subscribe_messages=True,  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 615, in _connect

  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    raise err
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 603, in _connect
        sock.connect(socket_address)
ConnectionRefusedErrorresponse = self.parse_response(block=False, timeout=timeout): 
[Errno 111] Connection refused  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,    if not block and not conn.can_read(timeout=timeout):

  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    return self._parser.can_read(timeout)    
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 416, in can_read
exec(code, run_globals)
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    return self.read_from_socket(timeout=timeout,
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 429, in read_from_socket
        main()raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)

  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
redis.exceptions.ConnectionError: Connection closed by server.
    click.Group(commands=commands)(prog_name="bench")
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 201, in start_worker
    start_worker(
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 235, in start_worker
    worker.work(logging_level=logging_level, burst=burst)
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 644, in work
    self.register_death()
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 344, in register_death
    p.execute()
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Traceback (most recent call last):
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 71, in get_app_commands
    app_command_module = importlib.import_module(app + ".commands")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 201, in start_worker
    start_worker(
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 216, in start_worker
    with frappe.init_site():
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/__init__.py", line 341, in __enter__
    init(self.site)
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/__init__.py", line 248, in init
    setup_module_map()
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/__init__.py", line 1526, in setup_module_map
    for module in get_module_list(app):
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/__init__.py", line 1378, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/__init__.py", line 1327, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'
Traceback (most recent call last):
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 71, in get_app_commands
    app_command_module = importlib.import_module(app + ".commands")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 201, in start_worker
    start_worker(
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 216, in start_worker
    with frappe.init_site():
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/__init__.py", line 341, in __enter__
    init(self.site)
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/__init__.py", line 248, in init
    setup_module_map()
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/__init__.py", line 1526, in setup_module_map
    for module in get_module_list(app):
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/__init__.py", line 1378, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/nandamtejas/frappe-project/frappe-bench/apps/frappe/frappe/__init__.py", line 1327, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/nandamtejas/frappe-project/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
